from enum import Enum


class ConversationState(str, Enum):

    WELCOME = "WELCOME"

    MONEY_LOST = "MONEY_LOST"

    AMOUNT = "AMOUNT"

    MESSAGE_AVAILABLE = "MESSAGE_AVAILABLE"

    MESSAGE_INPUT = "MESSAGE_INPUT"

    FRAUD_CHANNEL = "FRAUD_CHANNEL"

    INCIDENT_TIME = "INCIDENT_TIME"

    DESCRIPTION = "DESCRIPTION"

    CLASSIFICATION = "CLASSIFICATION"

    COMPLETED = "COMPLETED"